config/routes.rb
Rails.application.routes.draw do

root to: "welcome#index"

get 'show' => 'users#show'


namespace :api, defaults: { format: :json } do
  match '/events', to: 'events#preflight', via: [:options]
  resources :events, only: [:create]
end

resources :registered_applications

devise_for :users, :controllers => { registrations: 'registrations' }



end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                        :integer          not null, primary key
#  name                      :string
#  registered_application_id :integer
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#

class Event < ActiveRecord::Base
  belongs_to :registered_application

  #Validations
  validates :name, presence: true

end

app/models/registered_application.rb
# == Schema Information
#
# Table name: registered_applications
#
#  id         :integer          not null, primary key
#  name       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  url        :string
#

class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events

  #validations

  validates :name, presence: true
  validates :url, presence: true

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string
#  last_name              :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

#------Relationships
has_many :registered_applications

validates :first_name, presence: true, length: {minimum: 2}
validates :last_name, presence: true, length: {minimum: 3}
validates :email, presence: true



end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_filter :set_access_control_headers


  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    
    if registered_application.nil?
      render json: { error: "Unregistered application" }, status: :unprocessable_entity
    else
      @event = registered_application.events.build( event_params )
      if @event.save
        render json: @event, status: :created
      else
        render json: { error: @event.errors }, status: :unprocessable_entity
      end
    end
  end

  def preflight
    head 200
  end

  def set_access_control_headers
    #Allow requests from any origin
    headers['Access-Control-Allow-Origin'] = '*'
    #Permit POST GET OPTIONS request methods
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    # Allows the header 'Content-Type' to declare the type of data being sent
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  private

  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController


  def show
    @reg_app = RegisteredApplication.find(params[:id])
    @events = @reg_app.events.group_by(&:name)
  end

  def edit
    @reg_app = RegisteredApplication.find(params[:id])
  end

  def new
    @reg_app = RegisteredApplication.new
  end

  def create
    @reg_app = RegisteredApplication.new(app_params)
    @reg_app.user = current_user

    if @reg_app.save
      flash[:notice] = "Application Registered"
      redirect_to @reg_app
    else
      flash.now[:alert] = "Something went wrong. Please try again."
      render :new
    end
  end

  def update
    @reg_app = RegisteredApplication.find(params[:id])
    @reg_app.assign_attributes(app_params)

    if @reg_app.save
      flash[:notice] = "Application Updated"
      redirect_to @reg_app
    else
      flash[:notice] = "Something went wrong. Please try again."
      render :edit
    end
  end

  def destroy
    @reg_app = RegisteredApplication.find(params[:id])

    if @reg_app.destroy
      flash[:notice] = "Application Deleted"
      redirect_to root_path
    else
      flash[:notice] = "Something went wrong. Please try again."
      redirect_to request.referrer
    end
  end

private

  def app_params
    params.require(:registered_application).permit(:name, :url)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @reg_app = @user.registered_applications
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_controller_helper.rb
module RegisteredApplicationsControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Nav Bar  -->
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">

      <%= link_to "BlocMetrics", root_path, class: 'navbar-brand text-muted' %>

      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-left">
          <li> <%= link_to "About", "#" %> </li>
        </ul>

        <ul class= "nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li class="dropdown">
            <a data-toggle='dropdown' data-target='#'><%= current_user.first_name %> <b class="caret"> </b> </a>
          <ul class="dropdown-menu">
            <li> <%= link_to 'My Applications', show_path %> </li>
            <li> <%= link_to 'Edit Profile', edit_user_registration_path %> </li>
          </ul>
        </li>

         <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li> <%= link_to "Sign In", new_user_session_path %> </li>
        <li> <%= link_to "Sign Up", new_user_registration_path %> </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<div class="container">
  <% if flash[:notice] %>
  <div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
  <% elsif flash.now[:alert] %>
  <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash.now[:alert] %>
  </div>
  <% elsif flash[:alert] %>
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
</div>
<% end %>

<%= yield %>
</body>
</html>

app/views/registered_applications/edit.html.erb
<%= form_for @reg_app do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Application Name" %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control', placeholder: "Application Name" %>
  </div>

  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>

<% end %>

app/views/registered_applications/new.html.erb
<%= form_for @reg_app do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Application Name" %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control', placeholder: "Application Name" %>
  </div>

  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>

<% end %>

app/views/registered_applications/show.html.erb
<h1><%= @reg_app.name %></h1>
<%= link_to "Edit App", edit_registered_application_path(@reg_app), class:'btn-sm btn-warning' %>
<h1> Events </h2>
<% @events.each do |name, events| %>
<div>
  <%= name %> <span class="badge"><%= events.count %></span>

</div>
<% end %>

<div>
  <%= pie_chart @reg_app.events.group(:name).count %>
</div>
<br/>
<hr/>
<div>
  <p>Events by Day</p>
  <%= line_chart @reg_app.events.group_by_day(:created_at).count %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <h1> <%=current_user.first_name.capitalize %>'s Apps </h1>
    <% @reg_app.each do |app| %>
    <hr/>
    <%= link_to app.name, app %>
    -> <%= link_to "Cancel App", app, method: :delete, class:'btn-sm btn-danger', confirm: {data: "Are you sure you want to unregister this app?"} %>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>Blocmetrics</h1>
    <br/>
    <br/>
    <div class="btn-group">
      <% if user_signed_in?%>
        <%= link_to "Register your application", new_registered_application_path, class: "btn btn-info" %>
      <% else %>
        <%= link_to "Join the Club", new_user_registration_path, class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>